services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
      - ./config/media:/media
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Africa/Cairo
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0  # Optional: for Zigbee/Z-Wave
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  voice_streaming:
    container_name: voice-streaming
    build: 
      context: ./webrtc_backend
    network_mode: host
    environment:
      - TZ=Africa/Cairo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - ./webrtc_backend:/app

  # Optional: Nginx proxy for HTTPS (required for WebRTC)
  nginx:
    container_name: ha-nginx
    image: nginx:alpine
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    restart: unless-stopped
    depends_on:
      - homeassistant
      - voice_streaming